Hotel_P/Models/ErrorViewModel.cs
namespace Hotel_P.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hotel_P/Models/Room.cs
namespace Hotel_P.Models
{
    public class Room
    {

        public int Id { get; set; }
        public bool free { get; set; }
        public string room_type { get; set; }
        public int capacity { get; set; }
        public int floor { get; set; }
        public Room()
        {

        }

    }
}

Hotel_P/Models/reservation.cs
namespace Hotel_P.Models
{
    public class reservation
    {
        public int Id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }

        public string start_date    { get; set; }
        public string end_date  { get; set; }


    }
}

Hotel_P/Controllers/BookingController.cs
using Hotel_P.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using MySql.Data.MySqlClient;

namespace Hotel_P.Controllers
{
    public class BookingController : Controller
    {
        [HttpPost]
        public IActionResult Index(reservation cstm,int ID)
        {
            ViewBag.ID = ID;

            using (MySqlConnection con = new MySqlConnection("server=localhost;user=root;database=hotel_tr;port=3306;password=pass222"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand();
                cmd.Connection = con;
                string sql = "UPDATE `hotel_tr`.`rooms` SET `free` = '0' WHERE (`roomID` = '" + ViewBag.ID + "')";
                cmd.CommandText = sql;
                cmd.ExecuteNonQuery();
                sql = "INSERT INTO `hotel_tr`.`reservations` (`customerID`, `First_Name`, `Last_Name`, `Email`, `Phone`, `Address`, `Start_date`, `End_date`) VALUES ('" + cstm.Id+"', '"+cstm.fname+"', '"+cstm.lname+"', '"+cstm.email+"', '"+cstm.phone+"', '"+cstm.address+ "', '"+cstm.start_date+ "', '"+cstm.end_date+"')";
                cmd.CommandText = sql;
                cmd.ExecuteNonQuery();


                con.Close();
            }
            return View();
        }
    }
}

Hotel_P/Controllers/DatepickController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel_P.Controllers
{
    public class DatepickController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Hotel_P/Controllers/HomeController.cs
using Hotel_P.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using MySql.Data.MySqlClient;

namespace Hotel_P.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
             List<Room> rooms = new List<Room>();
            using (MySqlConnection con = new MySqlConnection("server=localhost;user=root;database=hotel_tr;port=3306;password=pass222"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from rooms WHERE free = TRUE", con);
                MySqlDataReader mySqlDataReader = cmd.ExecuteReader();

                while (mySqlDataReader.Read())
                {

                    Room rm;
                    rm = new Room();
                    rm.Id = Convert.ToInt32(mySqlDataReader["roomID"]);
                    rm.free = Convert.ToBoolean(mySqlDataReader["free"]);
                    rm.room_type = Convert.ToString(mySqlDataReader["room_type"]);
                    rm.capacity = Convert.ToInt32(mySqlDataReader["capacity"]);
                    rm.floor = Convert.ToInt32(mySqlDataReader["floor"]);

                    rooms.Add(rm);


                }

                con.Close();
            }
            return View(rooms);
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hotel_P/Controllers/ReservationController.cs
using Hotel_P.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using MySql.Data.MySqlClient;
using System.Drawing;

namespace Hotel_P.Controllers
{
    public class ReservationController : Controller
    {
        
        public IActionResult Index(int ID)
        {

            ViewBag.ID = ID;
            return View();
        }
        
       
    }
}

Hotel_P/Views/Booking/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Congrats";
}
<h2>Congrats!</h2>

Hotel_P/Views/Home/Index.cshtml
@model List<Room>
@{
    ViewData["Title"] = "Home Page";
}

<table class="table table-borderd">
	<thead>
		<tr>
			<th>Room Number</th>
			<th>Availability</th>
			<th>Room Type</th>
			<th>Capacity</th>
			<th>Floor</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
			<td>@item.Id</td>
			<td>@item.free</td>
			<td>@item.room_type</td>
			<td>@item.capacity</td>
			<td>@item.floor</td>
			<td>
				@using(Html.BeginForm("Index","Reservation",FormMethod.Post))
         {
           <input type="hidden" name="ID" value="@item.Id" />
           <input type="submit" value="Book" />
         }
			</td>
			</tr>
		}
	</tbody>
</table>

Hotel_P/Views/Reservation/Index.cshtml
@using Hotel_P.Models
   
@model reservation
@{
    ViewData["Title"] = "Reservation";
}

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


<h2>Room number @ViewBag.ID</h2>


@using(Html.BeginForm("Index","Booking",FormMethod.Post)){


    reservation ms;

        <span>The ID:</span> @Html.TextBoxFor(ms => ms.Id)<br /><br />
        @Html.ValidationMessageFor(ms => ms.Id)
        <span>First Name: </span> @Html.TextBoxFor(ms => ms.fname)<br /><br />
        @Html.ValidationMessageFor(ms => ms.fname)
        <span>Last Name: </span>@Html.TextBoxFor(ms => ms.lname)<br /><br />
        @Html.ValidationMessageFor(ms => ms.lname)
        <span>Email: </span> @Html.TextBoxFor(ms => ms.email)<br /><br />
        @Html.ValidationMessageFor(ms => ms.email)
        <span>Phone: </span>@Html.TextBoxFor(ms => ms.phone)<br /><br />
        @Html.ValidationMessageFor(ms => ms.phone)
        <span>Address: </span> @Html.TextBoxFor(ms => ms.address)<br /><br />
        @Html.ValidationMessageFor(ms => ms.address)
        <br />
        <span>From: </span>@Html.TextBoxFor(ms => ms.start_date)
        <span> To </span>@Html.TextBoxFor(ms => ms.end_date)<br /><br />
   


        <input type="hidden" name="ID" value="m" />
        <input type="hidden" name="ID" value="@ViewBag.ID" />
        <input type="submit" value="Book" />

    
             
         
}

Hotel_P/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hotel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Hotel_P.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Hotel_P</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js">
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>